spring:
  application:
    name: user-api
    password-regex: ^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*?&#])[A-Za-z\d@$!%*?&#]{8,}$
    password-regex-message: should have at least 8 characters, including letters, numbers and a special character.
    jwt:
      secret-key: 5h93fV0sG#kP8^mBZ!lX3qA$zJ2wEdYT

  h2:
    console:
      enabled: true
      path: /h2-console


  datasource:
    url: jdbc:h2:~/userapi;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    username: sa
    password: ""
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none
