@startuml

actor User as U
participant "UserController" as UC
participant "UserService" as US
participant "UserMapper" as UM
participant "JwtGenerator" as JG
participant "UserRepository" as UR
participant "Database" as DB

U -> UC : Sending request
UC -> UC : Validating request
UC -> US : createUser()
US -> UM : toEntity() - Mapping UserDto to User
UM --> US : Returning User
US -> JG : Generating token
JG --> US : Returning token
US -> US: Setting token to the user
US -> UR : saveUser()
US -> DB : Storing User
DB --> US: Returning User with ID
US -> UM : toDto() - Mapping User to UserDto
UM --> US: Returning UserDto
US --> UC : Returning UserDto
UC --> U : Returning response

@enduml